#!/bin/bash

#dockerized
export SPRING_PROFILES_ACTIVE=local
export KAFKA_HOST=kafka:29092
export MONGO_HOST=mongodb:27017
export REDIS_HOST=redis

#JVM
#docker run -p 8081:8080 \
#  --network seed-poc_default \
#  -e SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE \
#  -e KAFKA_HOST=$KAFKA_HOST \
#  -e MONGO_HOST=$MONGO_HOST \
#  -e REDIS_HOST=$REDIS_HOST \
#  -t library/books:1.0.0-jvm

#binarie
docker run -p 8080:8080 \
  --network seed-poc_default \
  -e SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE \
  -e KAFKA_HOST=$KAFKA_HOST \
  -e MONGO_HOST=$MONGO_HOST \
  -e REDIS_HOST=$REDIS_HOST \
  -t library/books:1.0.0


#binarie
#export SPRING_PROFILES_ACTIVE=local
#export KAFKA_HOST=localhost:9092
#export MONGO_HOST=localhost:27017
#export REDIS_HOST=localhost

#../build/native/nativeCompile/books
